### ISSUE TITLE
format yaml files consistently (with a pre-commit hook)

### ISSUE THREAD

**Issue by ghost** [riscv/docs-spec-template#22]
I don't know if there needs to be a discussion on the settings but I'll describe here my thoughts.

My PR would have the folllowing settings: 

```yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
```

Based on:

* defaults of yamlfmt IMO add too much whitespace
* these settings are a close match to what currently exists
* 2 spaces, in general is enough to denote indentation w/o extending lines into the the > MAX_LINE_LENGTH
* this formatting passes yamllint (if that was to be deployed)

PR to follow...
